name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Check out the code from the repository

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify the version of Node.js (optional)

      - name: Install dependencies
        run: npm install  # Install any necessary dependencies for your project

      - name: Build project (optional)
        run: npm run build  # If you have a build script (e.g., using Webpack)

      - name: Deploy to GitHub Pages
        run: npm run deploy  # Make sure you have a deploy script in your package.json

        env:
          IMGBB_API_KEY: ${{ secrets.IMGBB_API_KEY }}  # Inject the secret into the environment
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
          AIRTABLE_TABLE_NAME: ${{ secrets.AIRTABLE_TABLE_NAME }}
